# Generated by Django 5.1.5 on 2025-01-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
