# Generated by Django 5.1.5 on 2025-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_name_comment_username_comment_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images_files/'),
        ),
    ]
